audit_header: false
title: Kansas City Real Estate Video Blog with James Hern and Michael Hern
description: Our mission at The Hern Group is to be your best resource for Kansas City real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The The Hern Group, your professional Kansas City Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: James and Michael Hern
  title:
  license_number:
  about_markdown: |
    The Hern Group as a whole is recognized as an industry leader not only in the Midwest, but nationwide.  As a part of the largest real estate company in the world, Keller Williams Realty, The Hern Group consistently ranks in the top 100 agents out of 180,000 agents worldwide.  In additional to being a top-ranked real estate team nation-wide, Michael and James Hern are both Dave Ramsey endorsed local providers.

    Since launching in 2001 with just two agents, the Hern Group has helped more than 4,000 individuals and family buy or sell their home in the Kansas City metroplex.  If your interested in seeing how we can assist you with your buying or selling needs, contact us today at <a href="tel:1-800-274-5951">800-274-5951</a> or by email at <a href="mailto:info@hernhomes.com">info@hernhomes.com</a>.
  market: Kansas City
  brand: The Hern Group
  brokerage: Keller Williams Platinum Partner
  address: 1201 NE Windsor Drive.<br>Lee's Summit, MO 64086
  phone: 816-875-1744
  phone_type: James
  phone2: 816-529-4949
  phone2_type: Michael
  email: info@HernHomes.com
  url: https://www.HernHomes.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://www.experthomeoffers.com/Property-Value
  second_CTA_text: Home Search
  second_CTA_URL: https://www.hernhomes.com/listings/492

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "What’s Your Kansas City Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: http://www.experthomeoffers.com/Property-Value

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a Kansas City Home?"
    CTA_text2: "Search the entire MLS for your Kansas City home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://www.hernhomes.com/listings/492

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/theherngroup/
  linkedin_url:
  gplus_url:
  youtube_url:
  twitter_url: https://twitter.com/theherngroup
  instagram_url: https://www.instagram.com/theherngroup/
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url: https://podcasts.apple.com/us/podcast/kansas-city-real-estate-podcast-james-hern-michael/id1481120062

podcast:
  title: 'Kansas City Real Estate Podcast with James Hern and Michael Hern'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Kansas City Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from The Hern Group - your professional Kansas City Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Kansas City, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'James Hern and Michael Hern'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Kansas City Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#bf3125'
  theme_color: '#808080'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: rgba(0,0,0,.75)

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
